version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./code:/code"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./log/nginx:/var/log/nginx"
    networks:
      - local-nework
    depends_on:
      - php
  php:
    build: .
    volumes: 
      - "./code:/code"
      - "./log:/log"
    networks:
      - local-nework
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - local-nework
networks:
  local-nework:
    driver: bridge
